### ISSUE TITLE
Mouse libre en la pantalla y se activa solo en botones

### ISSUE THREAD

**Issue by jhcnewmedia** [HackathonWebdocs/villas#5]
Estimado Beto, por favor, nos puedes ayudar a mejorar lo siguiente: cómo hacer para que la zona de sensibilidad de la acción del mouse no sea la pantalla completa sino que específicamente en los botones. Como está ahora, tenemos problemas de usabilidad. Gracias!

**Comment by bertez** [comment]
hecho!
